### ISSUE TITLE
iso and rescue mode support

### ISSUE THREAD

**Issue by ghost** [thetechnick/hcloud-ansible#4]
I would be great to see support for iso images and rescue mode. Great module by the way.

**Comment by thetechnick** [comment]
Hi @acrom18,
thanks!

Booting a server into rescue mode is already implemented: https://github.com/thetechnick/hcloud-ansible/blob/master/docs/hcloud_server.md#options
I use it to install CoreOS: https://github.com/thetechnick/hcloud-ansible-kubernetes

Adding support for ISO images is on my todo list, but it might take a bit, because I want to add more test coverage to the existing server module before adding new features.

**Comment by thetechnick** [comment]
ISO mount/unmount is now supported (v0.3.2)
